In [1]:
# I am using ipython to work with deep learning interactivly.. I love this!

In [2]:
# The Neuron
inputs  = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0

output = sum([inputs[i]*weights[i] for i in range(len(inputs))]) + bias
print(output)

4.8


In [3]:
# The Layer
# We have Number of neurons in a layer
# Each Neuron has its own bias and different/same weights
inputs = [1.0, 2.0, 3.0, 2.5]
weights_list = [[0.2, 0.8, -0.5, 1.0], [0.5, -0.91, 0.26, -0.5], [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]

outputs = []
[outputs.append(sum([inputs[i]*weights_list[neuron][i] for i in range(len(inputs))]) + biases[neuron])\
    for neuron in range(len(weights_list))]

print(outputs) # Done!!

[4.8, 1.21, 2.385]


##### NUMPY

In [4]:
# Numpy is an easier and more convienient way to work with maths -------> Now We'll use Numpy
import numpy as np

In [5]:
# The Dot Product

inputs  = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0

output = np.dot(weights, inputs) + bias
print(output)

4.8


In [6]:
# Make sure to put the Bigger Dimension first --x--> Shape/Dimension Error!

inputs = [1.0, 2.0, 3.0, 2.5]
weights_list = [[0.2, 0.8, -0.5, 1.0], [0.5, -0.91, 0.26, -0.5], [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]

outputs = np.dot(weights_list, inputs) + biases
print(outputs)

[4.8   1.21  2.385]


In [7]:
# Batches

inputs = [[1.0, 2.0, 3.0, 2.5], [2.0, 5.0, -1.0, 2.0], [-1.5, 2.7, 3.3, -0.8]]
weights_list = [[0.2, 0.8, -0.5, 1.0], [0.5, -0.91, 0.26, -0.5], [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]

outputs = np.dot(inputs, np.array(weights_list).T) + biases

print(outputs)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


In [8]:
# Layers
inputs = [[1.0, 2.0, 3.0, 2.5], [2.0, 5.0, -1.0, 2.0], [-1.5, 2.7, 3.3, -0.8]]
weights_list = [[0.2, 0.8, -0.5, 1.0], [0.5, -0.91, 0.26, -0.5], [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]

weights_list2 = [[0.1, -0.14, 0.5], [-0.5, 0.12, -0.33], [-0.44, 0.73, -0.13]]
biases2 = [-1, 2, -0.5]

layer1_outputs = np.dot(inputs, np.array(weights_list).T) + biases
layer2_outputs = np.dot(layer1_outputs, np.array(weights_list2).T) + biases2

print(layer2_outputs)



[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


In [9]:
# So from here I will stop using ipynb --> we will convert this to an object!